# Build Stage
FROM golang as builder

ENV GO111MODULE=on
WORKDIR /app

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -ldflags="-w -s"  -o ds18b20-agent-go cmd/ds18b20-service/main.go

# Image stage
#FROM scratch
FROM alpine

WORKDIR /app

COPY --from=builder /app/ds18b20-agent-go .
COPY public public/

EXPOSE 8080
CMD ["/app/ds18b20-agent-go"]